---
#Install application
- include: installJira.yml

#Configure MYSQL backend
- include: configMysql.yml
  when: system_config_database and db_type == "mysql"

#Configure Postgres backend 
- include: configPostgres.yml
  when: system_config_database and db_type == "postgres"

#Register and launch service
- include: setupService.yml
  when: system_create_service
